import Header from '@/components/Header'
import Head from 'next/head'

import styled from 'styled-components'

// const Title = styled.h1`
//   font-size: 2rem;
//   color: #333;
//   font-family: 'Nunito Sans', sans-serif;
//   font-weight: 600;
// `

export default function Home() {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
      </div>
    </>
  )
}
