import Card from '@/components/Card'
import Header from '@/components/Header'
import Input from '@/components/Search'
import Head from 'next/head'

import styled from 'styled-components'

const Container = styled.div`
  max-width: 1450px;
  margin: 50px auto;
  padding: 0px 10px;
  /* border: 1px solid black; */
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container>
        <Input type="text" placeholder="Search for a country..." />

        <Card />
      </Container>
    </>
  )
}
